---
- name: Get Hashicorp GPG key
  ansible.builtin.get_url:
    url: "{{ hashicorp_gpg_url }}"
    dest: "/tmp/hashicorp_gpg"

- name: Add the Hashicorp GPG key
  ansible.builtin.shell:
    cmd: "gpg --dearmor /tmp/hashicorp_gpg | tee {{ hashicorp_gpg_keyring }}"
  become: true

- name: Verify the GPG key register as verify_gpg
  ansible.builtin.shell:
    cmd: "gpg --no-default-keyring --keyring {{ hashicorp_gpg_keyring }} --fingerprint"
  register: verify_gpg

- name: Do the actual verification with the known good --fingerprint"
  ansible.builtin.fail:
    msg: "Hashicorp GPG Key does not match with known good fingerprint"
    when: verify_gpg != hashicorp_gpg_fingerprint

- name: Add the Packer repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ hashicorp_gpg_keyring }} arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    state: present

- name: Add the Terraform repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ hashicorp_gpg_keyring }} arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

- name: Download package information
  ansible.builtin.apt:
    update_cache: yes
  
- name: Install Packer
  ansible.builtin.apt:
    name: packer={{ packer_version }}
    state: present

- name: Install Terraform
  ansible.builtin.apt:
    name: terraform={{ terraform_version }}
    state: present

- name: Check if Packer is correctly installed
  ansible.builtin.command:
    cmd: packer --version

- name: Check if Terraform is correctly installed
  ansible.builtin.command:
    cmd: terraform -version